package com.saveourtool.diktat.demo.controller

import com.saveourtool.diktat.demo.processing.CodeFix
import com.saveourtool.diktat.demo.views.CodeForm
import com.saveourtool.diktat.demo.views.RulesSetTypes

import com.pinterest.ktlint.core.LintError
import com.pinterest.ktlint.core.ParseException
import org.slf4j.LoggerFactory

import java.io.File
import java.util.UUID

/**
 * Main [Controller] for spring boot
 */
class DemoController {
    @Synchronized
    private fun generateFileName(): String = UUID.randomUUID().toString()

    private fun getDemoFile(generatedName: String = generateFileName()): File = File("demo-$generatedName.kt")
    private fun getDemoConfig(generatedName: String = generateFileName()): File = File("diktat-analysis-$generatedName.yml")

    /**
     * @param configLines [String] of yaml config
     * @param generatedName autogenerated name
     * @return temp [File] that contains yaml config
     */
    fun prepareConfigFile(
        configLines: String,
        generatedName: String = generateFileName(),
    ) = getDemoConfig(generatedName).apply {
        writeText(configLines)
    }

    /**
     * @param codeFormHtml
     * @return a page name
     */
    @Suppress("TOO_LONG_FUNCTION")
    fun checkAndFixCode(codeFormHtml: CodeForm): CodeForm {
        val codeForm = codeFormHtml
        val generatedName = generateFileName()
        println(codeFormHtml.diktatConfig)
        val configFile = codeFormHtml.diktatConfig?.let {
            prepareConfigFile(it, generatedName)
        }
        println(configFile?.getPath())
        val file = getDemoFile(generatedName)
        file.writeText(codeForm.initialCode!!)
        val codeFix = CodeFix(codeForm.initialCode!!, codeFormHtml.ruleSet[0], configFile?.getPath())
        val result = runCatching {
            if (codeForm.fix) {
                codeForm.fixedCode = codeFix.fix(file.absolutePath)
            } else if (codeForm.check) {
                codeForm.fixedCode = codeForm.initialCode
                codeFix.check(file.absolutePath)
            }
        }
        when {
            result.isSuccess -> codeForm.warnings = codeFix.listOfWarnings.map { it.prettyFormat(file) }
            result.exceptionOrNull() is ParseException -> codeForm.warnings = listOf(result.exceptionOrNull().toString())
            else -> {
                val issueLink = if (RulesSetTypes.KTLINT in codeForm.ruleSet) "https://github.com/pinterest/ktlint/issues" else "https://github.com/saveourtool/diktat/issues"
                codeForm.warnings = listOf(
                    """
                        |Unhandled exception during tool execution, please create a ticket at $issueLink:
                        |${result.exceptionOrNull()!!.stackTraceToString()}
                    """.trimMargin())
                log.error("Running formatter returned unexpected exception", result.exceptionOrNull())
            }
        }
        file.delete()
        configFile?.delete()
        return codeForm
    }

    private fun LintError.prettyFormat(file: File) = "Warn ($line:$col) $detail"
        .replace(file.absolutePath, "\"example_file_name\"")

    companion object {
        private val log = LoggerFactory.getLogger(DemoController::class.java)
        private const val PAGE_NAME = "demo"
    }
}
