package com.huawei.diktat.demo.views

import com.huawei.rri.fixbot.ruleset.huawei.constants.Warnings;

data class CodeForm(val code: String? = null,
                    val checkClassNameIncorrect: Boolean? = null,
                    val checkPackageNameMissing: Boolean? = null,
                    val checkPackageNameIncorrectCase: Boolean? = null,
                    val checkPackageNameIncorrectPrefix: Boolean? = null,
                    val checkPackageNameIncorrectSymbols: Boolean? = null,
                    val checkPackageNameIncorrectPath: Boolean? = null,
                    val checkObjectNameIncorrect: Boolean? = null,
                    val checkVariableNameIncorrectFormat: Boolean? = null,
                    val checkVariableNameIncorrect: Boolean? = null,
                    val checkConstantUppercase: Boolean? = null,
                    val checkVariableHasPrefix: Boolean? = null,
                    val checkIdentifierLength: Boolean? = null,
                    val checkEnumValue: Boolean? = null,
                    val checkGenericName: Boolean? = null,
                    val checkFunctionBooleanPrefix: Boolean? = null,
                    val checkFileNameMatchClass: Boolean? = null,
                    val checkMissingKdocTopLevel: Boolean? = null,
                    val checkMissingKdocClassElements: Boolean? = null,
                    val checkKdocWithoutParamTag: Boolean? = null,
                    val checkKdocWithoutReturnTag: Boolean? = null,
                    val checkKdocWithoutThrowsTag: Boolean? = null,
                    val checkBlankLineAfterKdoc: Boolean? = null,
                    val checkKdocWrongSpacesAfterTag: Boolean? = null,
                    val checkKdocWrongTagsOrder: Boolean? = null,
                    val checkKdocNoNewlineAfterSpecialTags: Boolean? = null,
                    val checkKdocNoEmptyTags: Boolean? = null,
                    val checkKdocNoDeprecatedTag: Boolean? = null)
