package org.cqfn.diktat.demo.views

import org.springframework.web.multipart.MultipartFile

/**
 * A class containing data associated with text form on frontend
 */
data class CodeForm(var initialCode: String? = null,
                    // do not rename it to isFix or isCheck as it will break thymeleaf as getters are autogenerated
                    var fix: Boolean = false,
                    var check: Boolean = false,
                    var ruleSet: List<RulesSetType> = listOf(RulesSetType.DIKTAT, RulesSetType.KTLINT),
                    // no need to create hashcode/equals for this class. This class is not used in collections.
                    var diktatConfigFile: Array<MultipartFile>? = null,
                    var fixedCode: String? = null,
                    var warnings: List<String>? = null)
