package org.cqfn.diktat.demo.views

import org.springframework.web.multipart.MultipartFile

/**
 * A class containing data associated with text form on frontend
 * @property initialCode
 * @property fix do not rename it to isFix or isCheck as it will break thymeleaf as getters are autogenerated
 * @property check
 * @property ruleSet
 * @property diktatConfigFile no need to create hashcode/equals for this class. This class is not used in collections.
 * @property fixedCode
 * @property warnings
 */
data class CodeForm(var initialCode: String? = null,
                    var fix: Boolean = false,
                    var check: Boolean = false,
                    var ruleSet: List<RulesSetTypes> = listOf(RulesSetTypes.DIKTAT, RulesSetTypes.KTLINT),
                    var diktatConfigFile: Array<MultipartFile>? = null,
                    var fixedCode: String? = null,
                    var warnings: List<String>? = null)
